def create_standard_assessment():
    return [
        {
            "id": 1,
            "type": "MCQ",
            "difficulty": "Easy",
            "marks": 5,
            "question": "A project requirement is unclear. What should you do before implementing it?",
            "options": {
                "A": "Clarify the expected outcome and acceptance criteria",
                "B": "Choose an interpretation and avoid discussing it",
                "C": "Implement every possible interpretation",
                "D": "Wait until the deadline is close",
            },
            "correct_answer": "A",
            "explanation": "Confirming expected outcomes prevents avoidable rework.",
        },
        {
            "id": 2,
            "type": "MCQ",
            "difficulty": "Easy",
            "marks": 5,
            "question": "A result looks incorrect. What is the best first step?",
            "options": {
                "A": "Change several things at once",
                "B": "Verify the inputs and reproduce the issue",
                "C": "Assume the result is correct",
                "D": "Delete the result and continue",
            },
            "correct_answer": "B",
            "explanation": "Reproduction and input checks help isolate the cause.",
        },
        {
            "id": 3,
            "type": "MCQ",
            "difficulty": "Medium",
            "marks": 10,
            "question": "Two important tasks have conflicting deadlines. How should you prioritize them?",
            "options": {
                "A": "Work on whichever task is easiest",
                "B": "Do both at once without informing anyone",
                "C": "Compare impact and dependencies, then communicate tradeoffs",
                "D": "Delay both until priorities change",
            },
            "correct_answer": "C",
            "explanation": "Impact, dependencies, and clear communication support sound prioritization.",
        },
        {
            "id": 4,
            "type": "MCQ",
            "difficulty": "Medium",
            "marks": 10,
            "question": "A reviewer disagrees with your proposed approach. What is the most constructive response?",
            "options": {
                "A": "Reject the feedback without discussion",
                "B": "Ask about the concern and compare both approaches against the requirements",
                "C": "Escalate immediately without sharing context",
                "D": "Make the change without understanding the feedback",
            },
            "correct_answer": "B",
            "explanation": "Evaluating feedback against requirements helps the team choose a reasoned solution.",
        },
        {
            "id": 5,
            "type": "MCQ",
            "difficulty": "Hard",
            "marks": 15,
            "question": "A serious issue is discovered shortly before release. What is the best response?",
            "options": {
                "A": "Hide the issue to protect the release date",
                "B": "Make an unreviewed change directly in production",
                "C": "Assess impact, contain risk, and coordinate a mitigation plan with stakeholders",
                "D": "Assume another team will find it",
            },
            "correct_answer": "C",
            "explanation": "Impact assessment, containment, and coordination reduce release risk.",
        },
        {
            "id": 6,
            "type": "MCQ",
            "difficulty": "Hard",
            "marks": 15,
            "question": "A metric improved after a change. How should you check whether the change caused the improvement?",
            "options": {
                "A": "Compare against a baseline and account for other changes or confounding factors",
                "B": "Report causation immediately",
                "C": "Use only the most favorable measurement",
                "D": "Ignore the measurement period",
            },
            "correct_answer": "A",
            "explanation": "A baseline and consideration of confounding factors make conclusions more reliable.",
        },
    ]